baseurl: ""
url: "http://www.conceptsincomputerprogramming.com"
description: >-
  Is this the subtitle?
email: mike.abner@gmail.com
github_username: MikeAbner
theme: jekyll-theme-cayman
title: Concepts In Computer Programming
