baseurl: ""
url: "http://www.conceptsincomputerprogramming.com"
description: >-
  Concepts in Computer Programming
email: mike.abner@gmail.com
github_username: MikeAbner
theme: jekyll-theme-cayman
title: Concepts In Computer Programming
