baseurl: ""
url: "http://www.conceptsincomputerprogramming.com"
title: Concepts In Computer Programming
description: A Software Development Curriculum
email: mike.abner@gmail.com
github_username: MikeAbner
theme: jekyll-theme-cayman

